name             'oun-webapp'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures oun-webapp'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends 'oun'
depends 'composer', '>= 0.0.5'
depends 'nginx'
depends 'rbenv'
depends 'nodejs'
depends 's3_file', '>= 2.1.0'
depends 'oun-sensu'
depends 'sensu'
