name             'oun-eec'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures oun-eec'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends 'monit-ng', '= 2.3.0'
depends 'oun'
depends 'oun-ServiceAPI'
depends 'nodejs'
depends 'oun-sensu'
depends 'sensu'
