name             'oun-ops'
maintainer       'One University Network'
maintainer_email 'ops@oneuni.net'
license          'All rights reserved'
description      'Installs/Configures oun-ops'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'oun'
depends          'oun-sensu'
depends          'sensu'
depends          'rbenv'
issues_url       'http://oneuni.net'
source_url       'http://oneuni.net'
depends          's3_file', '~> 2.7.0'
