name             'oun-wso2is'
maintainer       'One University Network'
maintainer_email 'ops@oneuni.net'
license          'All rights reserved'
description      'Installs/Configures oun-wso2is'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.1'
depends          'java', '~> 1.39.0'
depends          's3_file', '~> 2.7.0'
depends          'oun'
issues_url       'http://oneuni.net'
source_url       'http://oneuni.net'
depends 'oun-sensu'
depends 'sensu'
