VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "chefsolo.local"
  config.vm.network "private_network", ip: "192.168.234.3"
  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path = './Berksfile'
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 8443
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 4
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "80"]
  end
  config.omnibus.chef_version = :latest
  config.vm.provision "chef_solo" do |chef|
  chef.roles_path = "."
  chef.add_role "chefsolo"
 end
end
