name             'oun-ServiceAPI'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures oun-ServiceAPI'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.5'
depends 'php', '>= 1.1.8'
depends 's3_file', '>= 2.1.0'
depends 'composer', '>= 0.0.5'
depends 'oun'
depends 'oun-sensu'
depends 'sensu'
depends 'logrotate'
